### PR TITLE
Implementation report for Bridgy Fed

### PR DESCRIPTION
**Pull request by snarfed**

### CODE REVIEW

**Comment by nightpool** [comment]
implementations reports use the interactive interface at https://test.activitypub.rocks/ now! the MD file in this repo is old

**Comment by nightpool** [comment]
(Also, you should be using the "federated server" option, not the "server" option, by AP terminology)

**Comment by snarfed** [comment]
@nightpool thanks! updated to federated server.

hand writing this report was much easier than using the interactive form generator, since bridgy fed is a bit unusual. ideally i'd rather adapt this as it is, if possible...?

**Comment by nightpool** [comment]
I found the same thing with mastodon, but I think it's more useful for them to have a binary yes/no on different features to get a sense of what things people are implementing.

@cwebber would be able to make a better call on this though, I only know about the new one because I filled out the automated impl report for mastodon yesterday.

**Comment by cwebber** [comment]
Heya @snarfed, no need to redo.  I'll do the conversion to the new format myself.  My fault for not doing full deprecation of the existing pages.  Thank you for your submission!

**Comment by snarfed** [comment]
thank you @cwebber!

**Comment by cwebber** [comment]
This should be pulled in now, see https://activitypub.rocks/implementation-report/

The one thing that's missing is I marked some of the ones for the client with `not-applicable*` since those don't follow the protocol exactly though they do support some of the behavior... the asterisk means you can hover to see a comment.

Let me know if you see something I missed.  Thank you!

**Comment by snarfed** [comment]
thanks @cwebber, looks great!

**Comment by cwebber** [comment]
Heya @snarfed ... so it turns out there were some items I forgot to put on the implementation report, which is my bad.  We have enough implementations of those items where we aren't blocked from going to PR / Rec but it would be nice to have responses from the implementations that would like to have complete reports on there.  If you go to: https://activitypub.rocks/implementation-report/

you can see some are marked "missing"... if you hover over their symbols you'll see their descriptions.  If you want to let me know which ones are yes / no I can update it pretty easily!

Sorry about this, and thanks in advance, assuming you're up for it!

**Comment by snarfed** [comment]
@cwebber hey, sure, no problem! happy to.

```
inbox:delivery:sharedInbox No
inbox:delivery:sharedInbox:deliver-to-inbox-if-no-sharedInbox N/A
inbox:accept:create Yes
inbox:accept:delete No
inbox:accept:delete:tombstone No
inbox:accept:follow:generate-accept-or-reject N/A
inbox:accept:accept:add-actor-to-users-following N/A
inbox:accept:reject:does-not-add-actor-to-users-following N/A
inbox:accept:announce:add-to-shares-collection Yes, indirectly, via webmention
inbox:accept:undo No
```

also, bridgy fed's current implementation report currently has _Free/Libre/Open Source? no_. mind changing that to yes?

**Comment by cwebber** [comment]
Updated everything (including the FOSS flag).  Thank you so much!

**Pull request closed without merging**
