### PR TITLE
Implementation Report Template

### PR DESCRIPTION
**Pull request by gobengo**
Readable version: https://github.com/gobengo/activitypub/blob/implementation-reports/implementation-reports/TEMPLATE.md

Seeking input here on general structure. I think probably the "Feature Acceptance Criteria" should be assertions in the test suite, and not checkboxes in the implementation report. If others agree, then gather those bullets can be the basis of a test suite.

* Implementation information
* Client Section (remove if inapplicable)
  * ...Client Feature
    * ...Feature Acceptance Criteria
* Servers (remove if inapplicable)
  * ...Server Feature
    * ...Feature Acceptance Criteria

I started my list of "Features" from the Exit Criteria features enumerated in 2.2. However, I am also grepping through the normative language of the spec, and some MUSTs describe behaviors outside of the 2.2 Features (e.g. Object Retrieval). Not sure if that's a problem, just pointing it out, as it could lead to there being 2 implementations of each Exit Criteria feature, but with all of those implementations ignoring MUSTs in the spec.
@cwebber do you think it's worth adding any of the following features as relevant for Exit Criteria?
* Object Retrieval
* Inbox Retrieval

I also filed #173 while working on this.

### CODE REVIEW

**Comment by gobengo** [comment]
I believe this now has all all the Client requirements backed by normative language

**Comment by cwebber** [comment]
This looks really good.  Thank you for your amazing work on it!  And sorry it took me *so long* to review it.

I think everything looks good to go and ready to merge, I'm just thinking of adding one thing... the [upload media section](https://www.w3.org/TR/activitypub/#uploading-media) of the document asks for the user to provide both the file and also a shell of the object (and for the server to expect / process that).  Maybe that should be added to the implmeentation report as well, or do you think that's already covered from the present wording?

**Comment by gobengo** [comment]
Do you mean having 2 new bullets for servers?
* accepts uploadedMedia file parameter
* accepts uploadedMedia object parameter

**Comment by cwebber** [comment]
That sounds good to me.  I'm going to merge this with that change.  Sound good to you?

**Comment by gobengo** [comment]
Yes

**Pull request merged**
