### PR TITLE
Rename OAuth endpoints to match RFC6749

### LINKED ISSUE #191: OAuth 2 token endpoint missing
Currently, an `Actor` object's `endpoints` contains a `oauthClientAuthorize`, which I would read as the authorization endpoint from RFC 6749. However, this doesn't allow the ActivityPub client to use the authorization code grant. Adding a token endpoint to the `endpoints` would allow people to properly implement the entire OAuth 2.0 flow.

### PR DESCRIPTION
**Pull request by strugee**
I REALLY am not confident that the text here makes sense so cc @aaronpk for a quick sanity check

Fixes #191

### CODE REVIEW

**Comment by aaronpk** [comment]
That text is fine. You didn't want to go with the values `authorization_endpoint` and `token_endpoint` that OpenID Connect is using?

**Comment by strugee** [comment]
AFAICT this is what we resolved to do:

> RESOLUTION: close https://github.com/w3c/activitypub/issues/191 by adding properties with names from OAuth2 spec and revising current oauthClientAuthorize property name

From https://www.w3.org/wiki/Socialwg/2017-04-18-minutes#item03

**Comment by strugee** [comment]
Unless you meant `oauthAuthorizationEndpoint` vs. `authorization_endpoint`? The camelcase seemed to fit in better with most of the other stuff in the JSON but I'm not attached to it. @cwebber?

**Comment by gobengo** [comment]
This pull as-is seems like a good way of fulfilling that resolution. i.e. the wording makes sense.

OIDC folks are also working in IETF on a standards-track doc to generalize that vocabulary for ["OAuth 2.0 Authorization Server Metadata"](https://tools.ietf.org/html/draft-ietf-oauth-discovery-06)

I think activitypub should just define an 'authorizationServer' relation whose value is a URL. Clients could then perform OAuth Discovery on that URL and take it from there. This takes ActivityPub out of the business of worrying about which subset of all those metadata properties might be needed, deciding whether to under_case or camelCase, and also leaves room open for other types of authorizationServers or discovery protocols.

**Comment by strugee** [comment]
That generally makes sense to me, but AFAICT OAuth Discovery is still a draft. Plus it's probably too late for normative changes like that...

**Comment by gobengo** [comment]
@strugee IETF OAuth Discovery may be a draft, but it's kind of just a proxy for a much more solid and widely used OpenID Foundation [OIDC Discovery spec](https://openid.net/specs/openid-connect-discovery-1_0.html).

Given that all of ActivityPub's Auth Section 9 is non-normative, what do you mean by too late for normative changes?

**Comment by strugee** [comment]
Oh, my bad. I forgot that section was non-normative :P

**Comment by cwebber** [comment]
I'm willing to merge this, but I'm unsure if we want to do what @gobengo suggests.

There's also the challenge that we discussed removing all the endpoints after last meeting, but after the after-meeting meeting (!) I'm not sure if that's what's happening or not still?

**Comment by cwebber** [comment]
Ah right, since we had the resolution, I'm going to merge this as-is, since it fulfills that resolution!

I'm open to further alterations to the oauth workflow but I think those should be filed as a separate ticket.

**Pull request merged**
